safe:        false
auto:        false
server:      false
server_port: 4000
destination: /Users/mijndert/Sites/mijndertstuij-nl

future:      true
lsi:         false
pygments:    true
markdown:    maruku
permalink:   /:year-:month/:title.html

maruku:
  use_tex:    false
  use_divs:   false
  png_engine: blahtex
  png_dir:    images/latex
  png_url:    /images/latex

rdiscount:
  extensions: []